module.exports = [
  {
    value: "trending",
    label: "Trending",
    icon: "fas fa-fire",
    color: "#fe424d",
  },
  { value: "farms", label: "Farms", icon: "fas fa-tree", color: "#8b6914" },
  {
    value: "beach",
    label: "Beach Cabins",
    icon: "fas fa-water",
    color: "#0099ff",
  },
  {
    value: "iconic",
    label: "Iconic Cities",
    icon: "fas fa-city",
    color: "#666666",
  },
  { value: "luxury", label: "Luxury", icon: "fas fa-crown", color: "#ffd700" },
  {
    value: "mountains",
    label: "Mountains",
    icon: "fas fa-mountain",
    color: "#8b7355",
  },
  { value: "desert", label: "Desert", icon: "fas fa-sun", color: "#ffa500" },
  { value: "forest", label: "Forest", icon: "fas fa-leaf", color: "#228b22" },
  {
    value: "adventure",
    label: "Adventure",
    icon: "fas fa-person-hiking",
    color: "#ff6347",
  },
  {
    value: "pet-friendly",
    label: "Pet-Friendly",
    icon: "fas fa-paw",
    color: "#ff69b4",
  },
  {
    value: "lake",
    label: "Lake Houses",
    icon: "fas fa-water",
    color: "#1e90ff",
  },
  {
    value: "camping",
    label: "Camping",
    icon: "fas fa-campground",
    color: "#6b8e23",
  },
  {
    value: "treehouse",
    label: "Treehouses",
    icon: "fas fa-tree",
    color: "#2e8b57",
  },
  {
    value: "villa",
    label: "Villas",
    icon: "fas fa-umbrella-beach",
    color: "#ff7f50",
  },
  {
    value: "ski",
    label: "Ski Chalets",
    icon: "fas fa-snowflake",
    color: "#00bfff",
  },
  { value: "island", label: "Islands", icon: "fas fa-ship", color: "#20b2aa" },
  {
    value: "cave",
    label: "Cave Stays",
    icon: "fas fa-dungeon",
    color: "#808080",
  },
  {
    value: "boat",
    label: "Houseboats",
    icon: "fas fa-sailboat",
    color: "#4682b4",
  },
  {
    value: "castle",
    label: "Castles",
    icon: "fas fa-chess-rook",
    color: "#708090",
  },
  {
    value: "tiny-home",
    label: "Tiny Homes",
    icon: "fas fa-house",
    color: "#cd853f",
  },
  {
    value: "countryside",
    label: "Countryside",
    icon: "fas fa-seedling",
    color: "#3cb371",
  },
  {
    value: "pool",
    label: "With Pool",
    icon: "fas fa-person-swimming",
    color: "#00ced1",
  },
  {
    value: "glamping",
    label: "Glamping",
    icon: "fas fa-igloo",
    color: "#daa520",
  },
  {
    value: "heritage",
    label: "Heritage",
    icon: "fas fa-landmark",
    color: "#b8860b",
  },
  {
    value: "wellness",
    label: "Wellness",
    icon: "fas fa-spa",
    color: "#9370db",
  },
];
